### ISSUE TITLE
Change more icons

### ISSUE THREAD

**Issue by mobilegmYT** [mcpiscript/Planet#12]
No offence intended, but the current planet icon literally looks like it has vomit all over it. Here's some more vibrant icons I found:

![image](https://user-images.githubusercontent.com/44128563/159312674-f258c3f5-def3-4e42-a2f3-f0d2f91e139f.png)
![image](https://user-images.githubusercontent.com/44128563/159312695-40c7d237-3433-4a53-aa8e-a76775cf2f30.png)
![image](https://user-images.githubusercontent.com/44128563/159312732-510b01ae-3027-4d6c-b949-ff1ed242be0c.png)
![image](https://user-images.githubusercontent.com/44128563/159312747-f46981f5-2752-4be8-b286-e992ae6e40ec.png)

**Comment by leha-code** [comment]
The current icon will be kept. Dot.
