### ISSUE TITLE
GitHub pages still not up?

### ISSUE THREAD

**Issue by Grimet14** [mcpiscript/Planet#18]
GitHub pages still not up... make sure you select the website branch, and root.

**Comment by leha-code** [comment]
It's up for me, try deleting your cache or something

**Comment by leha-code** [comment]
Maybe go into private mode to test out

**Comment by Grimet14** [comment]
hmmm ok

**Comment by Grimet14** [comment]
ugh, still not up. Ima reboot

**Comment by Grimet14** [comment]
@leha-code Can you please put the direct url here?

**Comment by Grimet14** [comment]
nvm, I figured it out. Yes it works.
